/**
 * Shared type definitions for the simulation engine.
 * This file contains NO React imports — the simulation layer is framework-independent.
 */

import type { SimulationEvent } from "../events/types";

/**
 * Every entity in the simulation is one of these types.
 * Maps to the components users can drag onto the canvas.
 */
export type EntityType =
  | "client"
  | "api"
  | "database"
  | "cache"
  | "load_balancer"
  | "cdn"
  | "message_queue";

/**
 * How the simulation clock reports time.
 * All simulation time is in milliseconds (virtual).
 */
export type Timestamp = number;

/**
 * A unique identifier for a request as it flows through the system.
 * Generated by the Client and carried through every event.
 */
export type RequestId = string;

/**
 * A unique identifier for any entity instance in the simulation.
 */
export type EntityId = string;

/**
 * The result of running a simulation.
 * Immutable — produced once, consumed by playback.
 */
export interface SimulationResult {
  events: SimulationEvent[];
  metrics: MetricsSnapshot;
  duration: number; // total simulated time in ms
  warnings: string[];
  errors: string[];
  metadata: SimulationMetadata;
  /** Ids of Client entities in this run — see MetricsCollector's clientIds param. */
  clientIds: EntityId[];
}

/**
 * Metrics snapshot — a point-in-time capture of all metrics.
 * All metrics derive from the event timeline.
 */
export interface MetricsSnapshot {
  // Aggregate
  totalRequests: number;
  successfulRequests: number;
  failedRequests: number;
  successRate: number; // 0.0 - 1.0

  // Latency (ms)
  averageLatency: number;
  p50Latency: number;
  p95Latency: number;
  p99Latency: number;

  // Throughput (requests per second of simulation time)
  throughput: number;

  // Per-entity metrics
  entityMetrics: Record<EntityId, EntityMetrics>;
}

export interface EntityMetrics {
  utilization: number; // 0.0 - 1.0
  requestCount: number;
  errorCount: number;
  queueLength: number;
  /** Only present for entities that emit CACHE_HIT/CACHE_MISS (Cache, CDN). */
  cacheHitRate?: number; // 0.0 - 1.0
  /** Only present for entities whose CACHE_HIT/CACHE_MISS events carry an edgeIndex (CDN). */
  cdnEdges?: CDNEdgeMetrics[];
  /** Only present for load balancers — how many requests each downstream target received. */
  routingDistribution?: RoutingTargetMetrics[];
}

export interface RoutingTargetMetrics {
  targetId: EntityId;
  requests: number;
}

export interface CDNEdgeMetrics {
  edgeIndex: number;
  hitRate: number; // 0.0 - 1.0
  requests: number; // hits + misses seen at this edge
}

/**
 * Result of running the same architecture twice — once as-is, once with
 * one entity spliced out (see compareArchitectures.ts) — to show its
 * real, measured effect rather than asserting it.
 */
export interface ArchitectureComparison {
  withAverageLatency: number;
  withoutAverageLatency: number;
  withSuccessRate: number;
  withoutSuccessRate: number;
}

/**
 * Simulation metadata — info about the run itself.
 */
export interface SimulationMetadata {
  seed: number;
  version: string;
  generatedAt: string;
}

/**
 * Configuration for a simulation run, derived from the user's architecture.
 * This is the shape the workshop-bridge.ts converts canvas state into.
 */
export interface SimulationConfig {
  entities: EntityConfig[];
  connections: ConnectionConfig[];
  scenario: ScenarioDefinition;
  options: SimulationOptions;
}

export interface EntityConfig {
  id: EntityId;
  type: EntityType;
  position: { x: number; y: number };
  config: Record<string, unknown>;
}

export interface ConnectionConfig {
  source: EntityId;
  target: EntityId;
  latencyMs?: number;
  protocol?: string;
}

export interface ScenarioDefinition {
  id: string;
  title: string;
  trafficPattern: TrafficPattern;
  durationMs: number;
  failureEvents?: FailureEvent[];
}

export type TrafficPattern =
  | { type: "constant"; rate: number }
  | { type: "burst"; rate: number; interval: number; duration: number }
  | { type: "ramp"; startRate: number; endRate: number; duration: number };

export interface FailureEvent {
  timestamp: Timestamp;
  entityId: EntityId;
  failureType: string;
  durationMs?: number;
}

export interface SimulationOptions {
  seed: number;
  maxSteps?: number; // safety limit for runaway simulations
}
